baseURL = "https://usable.tools/"
canonifyURLs = "true"
languageCode = "en-us"
title = "USABLE Tools"

paginate = 12
summaryLength = 20


[params]

  mainSections = ["front_carousel"]

  [params.homepage_meta_tags]
    meta_description = "The USABLE project (Usable Security Apps by Leveraging End-users) is building feedback loops across the world, connecting digital security trainers working with at-risk communities, design experts, and open source tool developers."
    meta_og_title = "USABLE Tools"
    meta_og_type = "website"
    meta_og_url = "https://usable.tools"
    meta_og_image = "https://usable.tools/images/safe.png"
    meta_og_description = "The USABLE project (Usable Security Apps by Leveraging End-users) is building feedback loops across the world, connecting digital security trainers working with at-risk communities, design experts, and open source tool developers. "
    meta_twitter_card = "The USABLE project (Usable Security Apps by Leveraging End-users) is building feedback loops across the world, connecting digital security trainers working with at-risk communities, design experts, and open source tool developers. "
    meta_twitter_site = "@USABLE_tools"
    meta_twitter_creator = "@USABLE_tools"
#
  [params.contact_us]
    email = "connect@usable.tools"
    twitter = "https://twitter.com/USABLE_tools"
    github = "https://github.com/usable-tools"
    feed = "index.xml"

  [params.sub_footer]
    attribution = '</p>Usable tools is run and operated by <a href="https://internews.org">Internews</a>'
    copyright = "Â© Internews"
    license = '<img alt="CC" src="{{ .Site.BaseURL }}images/cc.svg" /> This work is licensed under a Creative Commons Attribution <a href="https://creativecommons.org">4.0 International License</a>'


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "blog"
	name = "Blog"
	url = "/blog"
	weight = 3

[[menu.main]]
  identifier = "events"
  name = "Events"
  url = "/events/"
  weight = 4

[[menu.main]]
  identifier = "personas"
	name = "Personas"
	url = "/personas/"
  weight = 5
